### ISSUE TITLE
Function to set image position

### ISSUE THREAD

**Issue by thobrock** [jhonatandarosa/cytoscape.js-supportimages#2]
Hey curupaco,
thanks for your extention! It works fine so far.

But is there a function to set the initial coordinates (x,y) for the image? (Where is the image drawed by default: 0,0?)
I went through your code and tried to figure it out by myself. But I could find this parameter/function.

Do you have a solution?

**Comment by jhonatandarosa** [comment]
Hi bioinf-ice, 
is nice to know that someone is using it. 

You can set initial coordinates when you add the image this way

``` javascript
var si = cy.supportimages();
si.addSupportImage({
    url: 'someimageurl',
    name: 'Test',
    bounds: {
        x: 100,
        y: 100
    }
});
```

Any ideas, suggestions or critics that helps improving the plugin are welcome :smile:

**Comment by thobrock** [comment]
Thanks a lot for your fast reply. It works!

(If I have some ideas, I will let you know.)
