### ISSUE TITLE
Not working with current version of cytoscape.js (v2.6.4)

### ISSUE THREAD

**Issue by thobrock** [jhonatandarosa/cytoscape.js-supportimages#3]
Today I wanted to update the js files in my project. But it seems that your cytoscape extension doesn't work with the current version anymore.

Cytoscape.js version I used before: 2.4.9
Current Cytoscape.js version: 2.6.4

~~I didn't tested the versions in between, therefor I can't tell which version broke your extension.~~

It seems the first version that doesn't work anymore is cytoscape.js v2.5.0: http://js.cytoscape.org/download/cytoscape.js-2.5.0.zip

It would be nice, if you can take a look into this problem.

**Comment by jhonatandarosa** [comment]
Hi, 
thanks for your feedback.
Didn't have much time to test with later versions yet, we're still using 2.4.0 in our application =/
Just committed the change. Seems to be working with 2.6.4 now.

**Comment by thobrock** [comment]
Wow... what a fast reply. Thanks for the fix. It works now.
