### ISSUE TITLE
3.x & 2.7.x support

### ISSUE THREAD

**Issue by ninadpchaudhari** [jhonatandarosa/cytoscape.js-supportimages#4]
Seems the Extension does not work on 3.x & 2.7.x

Does Cytoscape have an upgrade guide I can read and contribute to this extension?

EDIT: 
Found this:
 * https://github.com/cytoscape/cytoscape.js/issues/1092
 * http://blog.js.cytoscape.org/2017/04/11/3.0.0-release/#api-changes-and-migration

Not so skilled in Cytoscape, but trying myself. 
please do push if someone can get this done / help a bit.!

https://github.com/ninadpchaudhari/cytoscape.js-supportimages

**Comment by jhonatandarosa** [comment]
Hi @ninadpchaudhari,

thanks for opening the issue. 
We had not identified this yet as we still using older version of cytoscape.js

For time being I'm on vacation, but next week (26/03) I'm back at work and will take a closer look at the issue, and make it support 2.7.x e 3.x.

Hope you can wait till there =D

**Comment by ninadpchaudhari** [comment]
Omg, you are too sweet :D 

Have a wonderful vacation :-) 

Can I wait? Your reply itself matters a ton !! with limited luck, I was trying to solve it myself !!

See you later :)
Thank you again :)
