### ISSUE TITLE
npm package needs to be updated

### ISSUE THREAD

**Issue by ninadpchaudhari** [jhonatandarosa/cytoscape.js-supportimages#7]
- The update done 3 years ago (to support cytoscape 3.x) is not published to npm package.

[npm package page](https://www.npmjs.com/package/cytoscape-supportimages)

Just a note :
- Package works as expected with latest cytoscape if "cytoscape-supportimages.js" is downloaded from github.

**Comment by jhonatandarosa** [comment]
I haven't worked on the project for a long time.
I just updated the package in the [npm](https://www.npmjs.com/package/cytoscape-supportimages).
